# version: '3.8'
# services:
#   postgres_con:
#     image: postgres:latest
#     container_name: postgres_con
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 123456
#       POSTGRES_DB: TravelerRegistration
#     ports:
#       - "5432:5432"

#   backendtravelservice:
#     build: .
#     container_name: backendtravelservice
#     depends_on:
#       - postgres_con
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_con:5432/TravelerRegistration
#       SPRING_DATASOURCE_USERNAME: postgres
#       SPRING_DATASOURCE_PASSWORD: 123456
#     ports:
#       - "8000:8000"
