name: Backend Tests
on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: TravelerRegistration
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 4s
          --health-retries 2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Let database start
        run: sleep 10

      - name: Test database connection
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d TravelerRegistration -c "SELECT 'Database Connected!'"

      - name: Check existing tables in TravelerRegistration
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d TravelerRegistration -c "\dt"
