name: Backend Tests
on:
  push:
    branches:
      - main
      - dev
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables from GitHub Secrets
        run: |
          echo "SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> $GITHUB_ENV

      - name: Debug database settings
        run: |
          echo "Using database URL: $SPRING_DATASOURCE_URL"

      - name: Verify connected database
        run: |
          DB_NAME=$(PGPASSWORD=$SPRING_DATASOURCE_PASSWORD psql -h localhost -U $SPRING_DATASOURCE_USERNAME -d TravelerRegistration -tAc "SELECT current_database();")
          if [ "$DB_NAME" = "ERROR" ]; then
            echo " ERROR: Could not connect to the database"
            exit 1
          fi
          
          echo "Connected to database: $DB_NAME"
          
          if [ "$DB_NAME" != "TravelerRegistration" ]; then
            echo "ERROR: Not using the correct database!"
            exit 1
          else
            echo "Correct database is in use."
          fi
