name: Backend Tests
on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: TravelerRegistration
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 4s
          --health-retries 2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Let database start
        run: sleep 10

      - name: Create application.properties
        run: |
          echo "spring.datasource.url=jdbc:postgresql://localhost:5432/${{ secrets.DB_NAME }}" >> src/main/resources/application.properties
          echo "spring.datasource.username=${{ secrets.DB_USER }}" >> src/main/resources/application.properties
          echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> src/main/resources/application.properties
          echo "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect" >> src/main/resources/application.properties
          echo "spring.jpa.hibernate.ddl-auto=create" >> src/main/resources/application.properties
          # Additional non-sensitive properties can be added here

      - name: Check existing tables in TravelerRegistration
        run: |
          DB_NAME=$(PGPASSWORD=postgres psql -h localhost -U postgres -d TravelerRegistration -tAc "SELECT current_database();")
          
          if [ "$DB_NAME" = "ERROR" ]; then
            echo " ERROR: Could not connect to the database"
            exit 1
          fi
          
          echo "Connected to database: $DB_NAME"
          if [ "$DB_NAME" != "TravelerRegistration" ]; then
            echo "Error: Not using the correct database"
            exit 1
          else
            echo "SPRING_DATASOURCE_URL: $SPRING_DATASOURCE_URL"
            echo "We are using the correct database."
